//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3_LastReal.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailOrder
    {
        public int ID_DetailOrder { get; set; }
        public Nullable<int> ID_Order { get; set; }
        public Nullable<int> ID_Product { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual OrderService OrderService { get; set; }
        public virtual Product Product { get; set; }
    }
}
