//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3_LastReal.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderService
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderService()
        {
            this.DetailOrders = new HashSet<DetailOrder>();
        }
    
        public int ID_Order { get; set; }
        public Nullable<int> ID_Computer { get; set; }
        public Nullable<System.DateTime> OrderTime { get; set; }
        public Nullable<int> Summary { get; set; }
    
        public virtual Computer Computer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailOrder> DetailOrders { get; set; }
    }
}
