//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3_LastReal.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int ID_Ticket { get; set; }
        public Nullable<int> ID_Vehicle { get; set; }
        public Nullable<System.TimeSpan> ArrivalTime { get; set; }
    
        public virtual Vehicle Vehicle { get; set; }
    }
}
